Repository cfpb/design-system, pull requests merged in 2020-12, with the labels that each got.

#1118 Remove utility individual packages from cfpb-atomic-component
  packages/cfpb-atomic-component/README.md
  packages/cfpb-atomic-component/src/utilities/dom-traverse.js
  packages/cfpb-atomic-component/src/utilities/object-assign.js
  packages/cfpb-atomic-component/src/utilities/object-assign/README.md
  packages/cfpb-atomic-component/src/utilities/object-assign/package.json
  packages/cfpb-atomic-component/src/utilities/type-checkers.js
  packages/cfpb-atomic-component/src/utilities/type-checkers/README.md
  packages/cfpb-atomic-component/src/utilities/type-checkers/package.json
  packages/cfpb-design-system/cfpb-design-system.js
  packages/cfpb-expandables/src/Expandable.js
  packages/cfpb-forms/src/organisms/MultiselectUtils.js
  packages/cfpb-tables/src/TableRowLinks.js
  packages/cfpb-tables/src/TableSortable.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/dom-traverse-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/object-assign-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/type-checkers-spec.js
Labels: lerna-changelog/breaking

#1119 Fix multiselect filtering
  packages/cfpb-forms/src/organisms/Multiselect.js
  test/browser/packages/cfpb-forms.js
Labels: lerna-changelog/bug

#1127 Encode inline SVGs for IE11 support
  packages/cfpb-icons/src/icons-svg-inline.js
Labels: lerna-changelog/bug

#1128 Multiselect: Pass clicks of the selected item's button down to the label it contains
  packages/cfpb-forms/src/organisms/Multiselect.js
Labels: lerna-changelog/bug

#1129 Linter fixes
  packages/cfpb-atomic-component/src/components/AtomicComponent.js
  scripts/gulp/test.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/standard-type-spec.js
Labels: lerna-changelog/internal

#1130 Multiselect: Explicitly set button type
  packages/cfpb-design-system/cfpb-design-system.js
  packages/cfpb-forms/src/organisms/Multiselect.js
Labels: lerna-changelog/bug

#1131 Update dom-traverse.js
  packages/cfpb-atomic-component/src/utilities/dom-traverse.js
Labels: lerna-changelog/bug

#1134 Update transitions and add transitions page to DS
  docs/_data/side-navigation.yml
  docs/_includes/variation-content.html
  docs/admin/config.yml
  docs/assets/css/main.less
  docs/assets/js/main.js
  docs/pages/transition-patterns.md
  packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
  packages/cfpb-expandables/src/ExpandableTransition.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/AlphaTransition-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/BaseTransition-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/MoveTransition-spec.js
Labels: lerna-changelog/breaking
