Repository cfpb/design-system, pull requests merged in 2020-11, with the labels that each got.

#1094 Migrate to ES6 export/import syntax
  packages/cfpb-atomic-component/src/components/Atom.js
  packages/cfpb-atomic-component/src/components/AtomicComponent.js
  packages/cfpb-atomic-component/src/components/Molecule.js
  packages/cfpb-atomic-component/src/components/Organism.js
  packages/cfpb-atomic-component/src/components/Page.js
  packages/cfpb-atomic-component/src/components/_Template.js
  packages/cfpb-atomic-component/src/mixins/Events.js
  packages/cfpb-atomic-component/src/utilities/config.js
  packages/cfpb-atomic-component/src/utilities/dom-closest/index.js
  packages/cfpb-atomic-component/src/utilities/object-assign/index.js
  packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
  packages/cfpb-atomic-component/src/utilities/type-checkers/index.js
  packages/cfpb-core/src/vars-breakpoints.js
  packages/cfpb-expandables/src/Expandable.js
  packages/cfpb-expandables/src/ExpandableTransition.js
  packages/cfpb-tables/src/Table.js
  packages/cfpb-tables/src/TableRowLinks.js
  packages/cfpb-tables/src/TableSortable.js
  test/unit-test/src/cfpb-atomic-component/src/components/AtomicComponent-spec.js
  test/unit-test/src/cfpb-atomic-component/src/mixins/Events-spec.js
  test/unit-test/src/cfpb-atomic-component/src/src-path.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/config-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/object-assign-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/AlphaTransition-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/BaseTransition-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/MoveTransition-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/type-checkers-spec.js
  test/unit-test/src/cfpb-expandables/src/Expandable-spec.js
  test/unit-test/src/cfpb-expandables/src/ExpandableTransition-spec.js
  test/unit-test/src/cfpb-tables/src/Table-spec.js
Labels: lerna-changelog/internal

#1098 Remove object shorthand to aid IE11
  docs/assets/js/redirect-banner.js
  docs/assets/js/sidebar.js
  packages/cfpb-atomic-component/src/utilities/type-checkers/index.js
  webpack.config.docs.js
Labels: lerna-changelog/bug

#1099 Update "feedback-forms" page
  docs/pages/feedback-forms.md
Labels: netlify-cms/pending_publish

#1096 Migrate multiselect into design system
  docs/_data/side-navigation.yml
  docs/assets/js/main.js
  docs/pages/dropdowns.md
  jest.config.js
  packages/cfpb-atomic-component/src/components/AtomicComponent.js
  packages/cfpb-atomic-component/src/utilities/dom-events/index.js
  packages/cfpb-atomic-component/src/utilities/dom-traverse/index.js
  packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
  packages/cfpb-expandables/src/Expandable.js
  packages/cfpb-expandables/src/ExpandableTransition.js
  packages/cfpb-forms/src/cfpb-forms.less
  packages/cfpb-forms/src/organisms/Multiselect.js
  packages/cfpb-forms/src/organisms/MultiselectModel.js
  packages/cfpb-forms/src/organisms/MultiselectUtils.js
  packages/cfpb-forms/src/organisms/multiselect.less
  packages/cfpb-forms/usage.md
  packages/cfpb-tables/src/Table.js
  test/unit-test/mocks/fileMock.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/dom-events-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/dom-traverse-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/AlphaTransition-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/BaseTransition-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/MoveTransition-spec.js
  test/unit-test/src/cfpb-expandables/src/ExpandableTransition-spec.js
  test/unit-test/src/cfpb-forms/src/organisms/Multiselect-spec.js
  test/unit-test/src/cfpb-forms/src/organisms/MultiselectModel-spec.js
  test/unit-test/src/cfpb-forms/src/organisms/MultiselectUtils-spec.js
Labels: lerna-changelog/breaking

#1104 Update "side-navigation" page
  docs/_data/side-navigation.yml
Labels: netlify-cms/draft

#1105 Hide multiselect horizontal scroll, wrap checkbox label text
  docs/pages/dropdowns.md
  packages/cfpb-forms/src/molecules/form-fields.less
  packages/cfpb-forms/src/organisms/multiselect.less
Labels: lerna-changelog/bug

#1106 Clean up DOM utilities
  packages/cfpb-atomic-component/src/utilities/dom-closest/README.md
  packages/cfpb-atomic-component/src/utilities/dom-closest/index.js
  packages/cfpb-atomic-component/src/utilities/dom-closest/package.json
  packages/cfpb-atomic-component/src/utilities/dom-events/index.js
  packages/cfpb-atomic-component/src/utilities/dom-traverse/index.js
  packages/cfpb-design-system/cfpb-design-system.js
  packages/cfpb-expandables/src/Expandable.js
  packages/cfpb-forms/src/organisms/Multiselect.js
  packages/cfpb-forms/src/organisms/MultiselectUtils.js
  packages/cfpb-tables/src/TableRowLinks.js
  packages/cfpb-tables/src/TableSortable.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/dom-closest-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/dom-events-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/dom-traverse-spec.js
Labels: lerna-changelog/bug
