Repository cfpb/design-system, pull requests merged in 2021-01, with the labels that each got.

#1139 Update "banners" page
  docs/pages/banners.md
Labels: netlify-cms/draft

#1142 Update "browse-pages" page
  docs/pages/browse-pages.md
Labels: netlify-cms/pending_publish

#1143 Update "updating-this-website" page
  docs/special-pages/updating-this-website.md
Labels: netlify-cms/draft

#1145 Update "data-visualization-1" page
  docs/pages/data-visualization-1.md
Labels: netlify-cms/pending_publish

#1146 Update "notifications" page
  docs/pages/notifications.md
Labels: netlify-cms/pending_publish

#1149 Update "filterable-list-pages" page
  docs/images/uploads/filterable-list-browse-wireframe.png
  docs/images/uploads/filterable-list-sublanding-wireframe.png
  docs/pages/filterable-list-pages.md
Labels: netlify-cms/draft

#1150 Update "filterable-list-pages" page
  docs/images/uploads/filterable-list-sublanding-wireframe.png
  docs/pages/filterable-list-pages.md
Labels: netlify-cms/draft

#1148 Update "text-inputs" page
  docs/pages/text-inputs.md
Labels: netlify-cms/pending_publish

#1151 Update "filterable-list-pages" page
  docs/pages/filterable-list-pages.md
Labels: netlify-cms/draft

#1147 Update "heroes" page
  docs/pages/heroes.md
Labels: netlify-cms/pending_publish

#1155 Update "heroes" page
  docs/pages/heroes.md
Labels: netlify-cms/pending_publish

#1158 InstantiateAll: Check for value in data-js-hook as opposed to existence of attribute
  packages/cfpb-atomic-component/src/utilities/atomic-helpers.js
Labels: lerna-changelog/bug

#1160 Update "tables" page
  docs/pages/tables.md
Labels: netlify-cms/pending_publish

#1159 Add unit test for data-hook and instantiateAll
  packages/cfpb-atomic-component/src/utilities/atomic-helpers.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers-spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/data-hook-spec.js
Labels: lerna-changelog/bug

#1163 Buttons: Darken red warning button text
  docs/pages/variables.md
  packages/cfpb-buttons/src/cfpb-buttons.less
  packages/cfpb-buttons/usage.md
Labels: lerna-changelog/bug

#1152 Update "data-visualization-1" page
  docs/images/uploads/parts-of-a-chart_012.png
  docs/images/uploads/parts-of-a-chart_013.png
  docs/images/uploads/parts-of-a-chart_titles.png
  docs/pages/data-visualization-1.md
Labels: netlify-cms/pending_review

#1162 Multiselect: Add down arrow to multiselect
  packages/cfpb-design-system/cfpb-design-system.js
  packages/cfpb-forms/src/organisms/Multiselect.js
  packages/cfpb-forms/src/organisms/multiselect.less
Labels: lerna-changelog/enhancement

#1154 Tables: Adjust table header style
  packages/cfpb-core/src/base.less
Labels: lerna-changelog/enhancement

#1161 Add MaxHeightTransition
  docs/assets/css/main.less
  docs/assets/js/main.js
  docs/pages/transition-patterns.md
  packages/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/transition.less
Labels: lerna-changelog/enhancement

#1166 Update "pagination" page
  docs/images/uploads/screen-shot-2021-01-22-at-5.02.03-pm.png
  docs/images/uploads/screen-shot-2021-01-22-at-5.02.30-pm.png
  docs/pages/pagination.md
Labels: netlify-cms/pending_publish

#1168 Update "pagination" page
  docs/pages/pagination.md
Labels: netlify-cms/pending_publish

#1169 Update "pagination" page
  docs/pages/pagination.md
Labels: netlify-cms/pending_publish

#1171 Update "photography" page
  docs/images/uploads/editorial_example_1.jpg
  docs/images/uploads/editorial_example_2.png
  docs/images/uploads/editorial_example_3.png
  docs/images/uploads/tone_example_2.png
  docs/images/uploads/tone_example_3.jpg
  docs/images/uploads/tone_example_4.jpg
  docs/images/uploads/tone_example_5.png
  docs/pages/photography.md
Labels: netlify-cms/pending_publish

#1172 Update "photography" page
  docs/images/uploads/photography_editorial_example_1.jpg
  docs/images/uploads/photography_editorial_example_2.png
  docs/images/uploads/photography_editorial_example_3.png
  docs/images/uploads/photography_event_example_1.jpg
  docs/images/uploads/photography_event_example_2.jpg
  docs/images/uploads/photography_event_example_3.jpg
  docs/pages/photography.md
Labels: netlify-cms/pending_publish

#1173 Update "photography" page
  docs/pages/photography.md
Labels: netlify-cms/pending_publish

#1174 Update "photography" page
  docs/pages/photography.md
Labels: netlify-cms/pending_publish
