Repository cfpb/design-system, pull requests merged in 2021-08, with the labels that each got.

#1266 Anchor linking: Fix live code example
  docs/assets/js/main.js
Labels: lerna-changelog/bug

#1267 Remove unnecessary u-hidden
  docs/assets/css/toggle-code-button.less
Labels: lerna-changelog/bug

#1278 Update "color" page
  docs/pages/color.md
Labels: netlify-cms/pending_publish

#1279 Update "typography" page
  docs/pages/typography.md
Labels: netlify-cms/pending_publish

#1263 Remove govuk tabs dependency and roll our own
  docs/_includes/variation-content.html
  docs/admin/src/widgets/pagePreviewTemplate.js
  docs/assets/css/tabs.less
  docs/assets/js/Tabs.js
  docs/assets/js/main.js
  docs/assets/js/tabs.js
  npm-packages-offline-cache/@types-estree-0.0.47.tgz
  npm-packages-offline-cache/acorn-8.2.4.tgz
  npm-packages-offline-cache/govuk-frontend-3.12.0.tgz
  package.json
  test/browser/docs/interstitial.js
  test/browser/docs/netlify-cms.js
  test/browser/docs/show-details.js
  test/browser/packages/cfpb-forms.js
  wdio.config.sauce.js
  yarn.lock
Labels: lerna-changelog/enhancement
