Repository cfpb/design-system, pull requests merged in 2021-09, with the labels that each got.

#1277 Add new card patterns
  docs/pages/cards.md
  packages/cfpb-layout/src/molecules/card.less
  packages/cfpb-layout/src/organisms/card-group.less
Labels: lerna-changelog/enhancement

#1286 Update "side-navigation" page
  docs/_data/side-navigation.yml
Labels: netlify-cms/pending_publish

#1287 Update dependencies: core-js, mini-css-extract-plugin, terser-webpack-plugin, webpack
  npm-packages-offline-cache/core-js-3.16.4.tgz
  npm-packages-offline-cache/core-js-3.17.2.tgz
  npm-packages-offline-cache/mini-css-extract-plugin-2.2.1.tgz
  npm-packages-offline-cache/mini-css-extract-plugin-2.2.2.tgz
  npm-packages-offline-cache/terser-webpack-plugin-5.2.1.tgz
  npm-packages-offline-cache/webpack-5.51.1.tgz
  npm-packages-offline-cache/webpack-5.51.2.tgz
  package.json
  yarn.lock
Labels: lerna-changelog/internal

#1288 Update "accessibility" page
  docs/pages/accessibility.md
Labels: netlify-cms/pending_publish

#1289 Update "home" page
  docs/special-pages/home.md
Labels: netlify-cms/pending_publish

#1282 Add inkwell organism
  docs/pages/wells.md
  packages/cfpb-layout/src/organisms/wells.less
Labels: lerna-changelog/enhancement

#1296 Fix multiselect infinite selections bug
  docs/pages/dropdowns.md
  packages/cfpb-forms/src/organisms/Multiselect.js
  packages/cfpb-forms/src/organisms/MultiselectModel.js
Labels: bug, lerna-changelog/bug

#1297 Cards: Set a white background on topic cards
  packages/cfpb-layout/src/molecules/card.less
Labels: lerna-changelog/bug

#1301 Add taglines component
  docs/_data/side-navigation.yml
  docs/_includes/global-eyebrow.html
  docs/assets/css/main.less
  docs/assets/css/tagline.less
  docs/pages/taglines.md
  docs/pages/wells.md
  packages/cfpb-core/src/utilities.less
  packages/cfpb-core/usage.md
  packages/cfpb-layout/src/organisms/wells.less
  packages/cfpb-typography/src/atoms/tagline.less
  packages/cfpb-typography/src/cfpb-typography.less
Labels: lerna-changelog/enhancement

#1302 Cards: Make highlight card colors accessible
  packages/cfpb-layout/src/molecules/card.less
  packages/cfpb-layout/src/organisms/wells.less
Labels: lerna-changelog/bug

#1303 Taglines: Fix quoting on data URI
  packages/cfpb-typography/src/atoms/tagline.less
Labels: lerna-changelog/bug
