Repository cfpb/design-system, pull requests merged in 2021-03, with the labels that each got.

#1200 Update "logo" page
  docs/images/uploads/logo_background_color.png
  docs/images/uploads/logo_background_pattern.png
  docs/images/uploads/logo_background_photo.png
  docs/images/uploads/logo_print_scale.png
  docs/images/uploads/logo_print_scale_2.png
Labels: netlify-cms/pending_publish

#1204 Update "logo" page
  docs/images/uploads/logo1_one-color.png
  docs/images/uploads/logo1_spanish.png
Labels: netlify-cms/pending_publish

#1205 Update "logo" page
  docs/images/uploads/logo_background_color.png
  docs/images/uploads/logo_background_pattern.png
  docs/images/uploads/logo_background_photo.png
Labels: netlify-cms/pending_publish

#1206 Update "logo" page
  docs/images/uploads/logo1_spanish.png
  docs/images/uploads/logo_desktop_scale.png
  docs/images/uploads/logo_mobile_scale.png
  docs/images/uploads/logo_print_scale.png
  docs/images/uploads/logo_print_scale_2.png
Labels: netlify-cms/pending_publish

#1208 Update "logo" page
  docs/images/uploads/logo1_spanish.png
  docs/images/uploads/logo_desktop_scale.png
  docs/images/uploads/logo_print_scale.png
  docs/images/uploads/logo_print_scale_2.png
Labels: netlify-cms/pending_publish

#1202 Update "data-visualization-1" page
  docs/pages/data-visualization-1.md
Labels: netlify-cms/pending_publish

#1209 Update "data-visualization-1" page
  docs/pages/data-visualization-1.md
Labels: netlify-cms/pending_publish

#1210 Update "data-visualization-1" page
  docs/pages/data-visualization-1.md
Labels: netlify-cms/pending_publish

#1212 Update "notifications" page
  docs/pages/notifications.md
Labels: netlify-cms/draft

#1213 Update "heading-hierarchy" page
  docs/pages/heading-hierarchy.md
Labels: netlify-cms/pending_publish

#1214 Fix imports in cfpb-design-system.js
  packages/cfpb-design-system/src/cfpb-design-system.js
Labels: lerna-changelog/bug
