Repository cfpb/design-system, pull requests merged in 2021-06, with the labels that each got.

#1241 Create "story-page" page
  docs/images/uploads/story_page_example.jpg
  docs/pages/story-pages.md
Labels: netlify-cms/draft

#1243 Update "side-navigation" page
  docs/_data/side-navigation.yml
Labels: netlify-cms/pending_publish

#1245 Update "heading-hierarchy" page
  docs/pages/heading-hierarchy.md
Labels: netlify-cms/pending_publish

#1246 cfpb-icons: remove unreferenced buying-car icon
  packages/cfpb-icons/src/icons/buying-car-round.svg
  packages/cfpb-icons/src/icons/buying-car.svg
Labels: lerna-changelog/bug

#1248 Update "video" page
  CHANGELOG.md
  docs/pages/video.md
Labels: netlify-cms/pending_publish

#1249 Update "video" page
  docs/pages/video.md
Labels: netlify-cms/pending_publish

#1250 Update "video" page
  docs/pages/video.md
Labels: netlify-cms/pending_publish

#1251 Update "video" page
  docs/pages/video.md
Labels: netlify-cms/pending_publish
