Repository cfpb/design-system, pull requests merged in 2023-05, with the labels that each got.

#1635 Remove o-expandable_target, o-expandable_header-left, o-expandable_header-right CSS classes
  docs/pages/expandables.md
  docs/pages/filterable-list-control-panels.md
  docs/special-pages/updating-this-website.md
  packages/cfpb-expandables/src/Expandable.js
  packages/cfpb-expandables/src/expandable.less
  packages/cfpb-expandables/usage.md
  test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers.spec.js
  test/unit-test/src/cfpb-expandables/src/Expandable.spec.js
Labels: lerna-changelog/breaking

#1640 Update "expandables" page
  docs/pages/expandables.md
Labels: netlify-cms/draft

#1642 cfpb-expandables: Consolidate `o-expandable_header` rules
  packages/cfpb-expandables/src/expandable.less
Labels: lerna-changelog/enhancement

#1644 Update eslint-plugin-jsdoc@44.2.4, webpack@2.82.1
  npm-packages-offline-cache/@es-joy-jsdoccomment-0.38.0.tgz
  npm-packages-offline-cache/@es-joy-jsdoccomment-0.39.4.tgz
  npm-packages-offline-cache/enhanced-resolve-5.13.0.tgz
  npm-packages-offline-cache/enhanced-resolve-5.14.0.tgz
  npm-packages-offline-cache/eslint-plugin-jsdoc-44.0.2.tgz
  npm-packages-offline-cache/eslint-plugin-jsdoc-44.2.4.tgz
  npm-packages-offline-cache/semver-7.5.1.tgz
  npm-packages-offline-cache/webpack-5.82.0.tgz
  npm-packages-offline-cache/webpack-5.82.1.tgz
  package.json
  yarn.lock
Labels: lerna-changelog/internal

#1646 Update jekyll@4.1.1
  Gemfile
Labels: lerna-changelog/internal

#1643 cfpb-layout: Remove `content-l__large-gutters`
  docs/pages/column-dividers.md
  docs/pages/sidebars-prefooters.md
  packages/cfpb-expandables/cfpb-expandables.css
  packages/cfpb-layout/cfpb-layout.css
  packages/cfpb-layout/src/cfpb-layout.less
  packages/cfpb-layout/usage.md
Labels: lerna-changelog/breaking

#1648 cfpb-core: Pulls in js-is-hidden utility from cf.gov
  packages/cfpb-core/src/utilities.less
Labels: lerna-changelog/enhancement

#1655 cfpb-icons: RTL certain icons
  docs/pages/iconography.md
  packages/cfpb-icons/src/cfpb-icons.less
Labels: lerna-changelog/enhancement
