Repository cfpb/design-system, pull requests merged in 2023-10, with the labels that each got.

#1756 Update "checkboxes" page
  docs/pages/checkboxes.md
Labels: netlify-cms/pending_publish

#1749 Update "dropdowns" page
  docs/pages/dropdowns.md
Labels: netlify-cms/pending_publish

#1761 Update "side-navigation" page
  docs/_data/side-navigation.yml
Labels: netlify-cms/pending_publish

#1762 Update "radio-buttons" page
  docs/pages/radio-buttons.md
Labels: netlify-cms/pending_publish

#1763 Update "checkboxes" page
  docs/pages/checkboxes.md
Labels: netlify-cms/pending_publish

#1764 Update "radio-buttons" page
  docs/pages/radio-buttons.md
Labels: netlify-cms/pending_publish

#1765 Update "radio-buttons" page
  docs/pages/radio-buttons.md
Labels: netlify-cms/pending_publish

#1767 Update "buttons" page
  docs/pages/buttons.md
Labels: netlify-cms/pending_publish

#1757 Refactor m-meta-header
  docs/pages/heading-hierarchy.md
  packages/cfpb-typography/src/molecules/meta-header.less
Labels: lerna-changelog/enhancement

#1769 Meta header: Adjust margin values
  docs/pages/heading-hierarchy.md
  packages/cfpb-typography/src/molecules/meta-header.less
  packages/cfpb-typography/usage.md
Labels: lerna-changelog/bug

#1771 Update "variables" page
  docs/pages/variables.md
Labels: netlify-cms/pending_publish

#1776 Update "typography" page
  docs/pages/typography.md
Labels: netlify-cms/pending_publish

#1780 Update "video" page
  docs/pages/video.md
Labels: netlify-cms/pending_publish

#1777 [Tag] Update styles per approved redesign
  packages/cfpb-forms/src/organisms/multiselect.less
  test/browser/packages/cfpb-forms.js
Labels: lerna-changelog/enhancement

#1786 Update "introductions" page
  docs/pages/introductions.md
Labels: netlify-cms/pending_publish

#1787 Update "wells" page
  docs/pages/wells.md
Labels: netlify-cms/pending_publish

#1789 Remove redundant margin | add responsive style code comments
  packages/cfpb-buttons/src/atoms/buttons.less
  packages/cfpb-core/src/base.less
  packages/cfpb-core/src/utilities.less
  packages/cfpb-layout/src/cfpb-layout.less
  packages/cfpb-layout/src/molecules/heroes.less
  packages/cfpb-layout/src/organisms/card-group.less
  packages/cfpb-layout/src/organisms/email-signup.less
  packages/cfpb-layout/src/organisms/featured-content-module.less
  packages/cfpb-layout/src/organisms/wells.less
  packages/cfpb-notifications/src/molecules/notification.less
  packages/cfpb-notifications/src/organisms/banner.less
  packages/cfpb-pagination/src/molecules/pagination.less
  packages/cfpb-tables/src/cfpb-tables.less
  packages/cfpb-typography/src/molecules/list.less
  packages/cfpb-typography/src/molecules/meta-header.less
  packages/cfpb-typography/src/molecules/pull-quote.less
Labels: lerna-changelog/bug

#1790 Update "introductions" page
  docs/pages/introductions.md
Labels: netlify-cms/pending_publish

#1791 Remove large pull quote
  packages/cfpb-typography/cfpb-typography.css
  packages/cfpb-typography/src/molecules/pull-quote.less
  packages/cfpb-typography/usage.md
Labels: lerna-changelog/breaking

#1792 Multiselect: Remove `display: -webkit-box` property
  packages/cfpb-forms/src/organisms/multiselect.less
Labels: lerna-changelog/bug

#1766 Remove `@btn-v-padding-modifier-ie`
  docs/pages/variables.md
  packages/cfpb-buttons/src/cfpb-buttons.less
  packages/cfpb-buttons/usage.md
Labels: lerna-changelog/enhancement

#1793 Update "wells" page
  docs/pages/wells.md
Labels: netlify-cms/pending_publish
