Repository cfpb/design-system, pull requests merged in 2023-02, with the labels that each got.

#1563 Add Summary component
  docs/_data/side-navigation.yml
  docs/assets/js/main.js
  docs/pages/summaries.md
  packages/cfpb-core/src/breakpoint-state.js
  packages/cfpb-expandables/src/Summary.js
  packages/cfpb-expandables/src/cfpb-expandables.less
  packages/cfpb-expandables/src/summary.less
  test/unit-test/src/cfpb-expandables/src/Summary-spec.js
Labels: lerna-changelog/enhancement

#1554 Tests: Add additional async/awaits
  test/browser/docs/interstitial.js
  test/browser/docs/netlify-cms.js
  test/browser/docs/show-details.js
  test/browser/packages/cfpb-expandables.js
  test/browser/packages/cfpb-forms.js
Labels: lerna-changelog/internal

#1573 Update "taglines" page
  docs/pages/taglines.md
Labels: netlify-cms/pending_publish

#1574 cfpb-notifications: Update notification.less to support arabic rtl layout
  packages/cfpb-notifications/src/molecules/notification.less
Labels: lerna-changelog/enhancement

#1576 Update wdio config to latest
  wdio.config.cjs
  wdio.config.sauce.cjs
Labels: lerna-changelog/internal

#1577 Migrate deprecated keyCode to KeyboardEvent.key
  packages/cfpb-forms/src/organisms/Multiselect.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/behavior.spec.js
  test/unit-test/src/cfpb-expandables/src/Expandable.spec.js
  test/unit-test/src/cfpb-forms/src/organisms/Multiselect.spec.js
  test/util/simulate-event.js
Labels: lerna-changelog/enhancement

#1575 cfpb-forms: Remove erroneously `inside` attribute left in Multiselect
  packages/cfpb-forms/src/organisms/Multiselect.js
Labels: lerna-changelog/bug

#1585 cfpb-atomic-component: Check if data-hook already contains a value before adding it again
  packages/cfpb-atomic-component/src/utilities/data-hook.js
Labels: lerna-changelog/enhancement

#1586 Fix stylelint config
  .stylelintrc.cjs
  docs/assets/css/code.less
  packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
  packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
  packages/cfpb-expandables/src/summary.less
  packages/cfpb-layout/src/molecules/card.less
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/BaseTransition.spec.js
Labels: lerna-changelog/bug

#1588 cfpb-forms: downcase event and fix event dispatch
  packages/cfpb-forms/src/organisms/Multiselect.js
Labels: lerna-changelog/breaking

#1589 cfpb-atomic-component: Don't set u-is-animating if transitionComplete handler is called right away
  packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
Labels: lerna-changelog/bug

#1592 Update "e-mail-signup-forms" page
  docs/pages/e-mail-signup-forms.md
Labels: netlify-cms/pending_publish

#1567 Create atomic utilities index.js file
  docs/assets/js/main.js
  packages/cfpb-atomic-component/package.json
  packages/cfpb-atomic-component/src/components/AtomicComponent.js
  packages/cfpb-atomic-component/src/index.js
  packages/cfpb-atomic-component/src/mixins/EventObserver.js
  packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
  packages/cfpb-atomic-component/src/utilities/behavior/behavior.js
  packages/cfpb-atomic-component/src/utilities/standard-type.js
  packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
  packages/cfpb-expandables/src/Expandable.js
  packages/cfpb-expandables/src/ExpandableTransition.js
  packages/cfpb-expandables/src/Summary.js
  packages/cfpb-forms/src/organisms/Multiselect.js
  test/browser/docs/show-details.js
  test/unit-test/src/cfpb-atomic-component/src/components/AtomicComponent.spec.js
  test/unit-test/src/cfpb-atomic-component/src/mixins/EventObserver.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/behavior.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/data-hook.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/standard-type.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/AlphaTransition.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/BaseTransition.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/MoveTransition.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/type-checkers.spec.js
Labels: lerna-changelog/breaking

#1594 Refactor email signup to simplify margins and handle different layouts
  docs/pages/e-mail-signup-forms.md
  packages/cfpb-layout/src/organisms/email-signup.less
Labels: lerna-changelog/enhancement
