Repository cfpb/design-system, pull requests merged in 2023-12, with the labels that each got.

#1848 Update "expandables" page
  docs/pages/expandables.md
Labels: netlify-cms/pending_publish

#1851 Update "alerts" page
  docs/pages/alerts.md
Labels: netlify-cms/pending_publish

#1850 Removed highlight and featured cards
  docs/pages/cards.md
  packages/cfpb-layout/src/molecules/card.less
Labels: lerna-changelog/breaking

#1852 Update "buttons" page
  docs/pages/buttons.md
Labels: netlify-cms/pending_publish

#1853 Update "helper-text" page
  docs/pages/helper-text.md
Labels: netlify-cms/pending_publish

#1854 Update "labels" page
  docs/pages/labels.md
Labels: netlify-cms/pending_publish

#1855 Update "links" page
  docs/pages/links.md
Labels: netlify-cms/pending_publish

#1857 Update "radio-buttons" page
  docs/pages/radio-buttons.md
Labels: netlify-cms/pending_publish

#1858 Update "selects" page
  docs/pages/selects.md
Labels: netlify-cms/pending_publish

#1859 Update "links" page
  docs/pages/links.md
Labels: netlify-cms/pending_publish

#1860 Update "lists" page
  docs/pages/lists.md
Labels: netlify-cms/pending_publish

#1861 Update "range-sliders" page
  docs/pages/range-sliders.md
Labels: netlify-cms/pending_publish

#1862 Update "range-sliders" page
  docs/pages/range-sliders.md
Labels: netlify-cms/pending_publish

#1863 Update "tables" page
  docs/pages/tables.md
Labels: netlify-cms/pending_publish

#1865 Update "checkboxes" page
  docs/pages/checkboxes.md
Labels: netlify-cms/pending_publish

#1867 Cards: Cleanup redundant CSS
  packages/cfpb-layout/src/molecules/card.less
Labels: lerna-changelog/bug

#1866 Format hero CSS by screensize
  packages/cfpb-layout/src/molecules/heroes.less
Labels: lerna-changelog/internal

#1869 Remove inkwell
  docs/pages/wells.md
  packages/cfpb-layout/src/organisms/wells.less
Labels: lerna-changelog/breaking
