Repository cfpb/design-system, pull requests merged in 2023-01, with the labels that each got.

#1535 Update "overview" page
  docs/pages/overview.md
Labels: netlify-cms/pending_publish

#1540 Update "tables" page
  docs/pages/tables.md
Labels: netlify-cms/pending_publish

#1524 Remove dom-traverse and update multiselect
  packages/cfpb-atomic-component/src/utilities/dom-traverse.js
  packages/cfpb-expandables/src/Expandable.js
  packages/cfpb-forms/src/organisms/Multiselect.js
  packages/cfpb-forms/src/organisms/MultiselectUtils.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/dom-traverse.spec.js
  test/unit-test/src/cfpb-forms/src/organisms/MultiselectUtils.spec.js
Labels: lerna-changelog/breaking

#1546 Update "banners" page
  docs/pages/banners.md
Labels: netlify-cms/pending_publish

#1551 Update "side-navigation" page
  docs/_data/side-navigation.yml
Labels: netlify-cms/pending_publish

#1558 Fix minor linter issues and remove extraneous comments
  docs/pages/banners.md
  packages/cfpb-atomic-component/src/utilities/atomic-helpers.js
  packages/cfpb-atomic-component/src/utilities/data-hook.js
  packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
  packages/cfpb-expandables/src/ExpandableTransition.js
  packages/cfpb-forms/src/organisms/Multiselect.js
Labels: lerna-changelog/internal

#1556 Add FlyoutMenu behavior to DS
  docs/assets/css/main.less
  docs/assets/js/main.js
  docs/pages/transition-patterns.md
  packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
  packages/cfpb-atomic-component/src/utilities/behavior/behavior.js
  packages/cfpb-atomic-component/src/utilities/transition/transition.less
  test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/behavior.spec.js
Labels: lerna-changelog/enhancement

#1559 Remove unneeded less imports
  packages/cfpb-buttons/src/atoms/buttons-with-icons.less
  packages/cfpb-buttons/src/cfpb-buttons.less
  packages/cfpb-buttons/src/molecules/button-groups.less
  packages/cfpb-expandables/src/cfpb-expandables.less
  packages/cfpb-forms/src/cfpb-forms.less
  packages/cfpb-layout/src/cfpb-layout.less
  packages/cfpb-notifications/src/cfpb-notifications.less
  packages/cfpb-pagination/src/cfpb-pagination.less
  packages/cfpb-typography/src/cfpb-typography.less
Labels: lerna-changelog/bug

#1557 Update anchor-js and eslint-plugin-jsdoc
  npm-packages-offline-cache/anchor-js-4.3.1.tgz
  npm-packages-offline-cache/anchor-js-5.0.0.tgz
  npm-packages-offline-cache/eslint-plugin-jsdoc-39.6.4.tgz
  npm-packages-offline-cache/eslint-plugin-jsdoc-39.6.6.tgz
  package.json
  yarn.lock
Labels: lerna-changelog/internal

#1562 Ignore some linting rules
  packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
  packages/cfpb-atomic-component/src/utilities/behavior/behavior.js
  packages/cfpb-forms/src/organisms/Multiselect.js
Labels: lerna-changelog/internal

#1553 Change task copy-icons to copy-assets
  CONTRIBUTING.md
  package.json
Labels: lerna-changelog/internal

#1564 Transitions: Enforce having both expand and collapse transitions
  packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
  packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.js
  packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
Labels: lerna-changelog/breaking

#1568 Remove DIRECTIONS bit values utility
  packages/cfpb-atomic-component/src/utilities/standard-type.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/standard-type.spec.js
Labels: lerna-changelog/breaking
