Repository cfpb/design-system, pull requests merged in 2023-07, with the labels that each got.

#1668 cfpb-layout: Fix breakout card margin
  packages/cfpb-layout/src/molecules/card.less
Labels: lerna-changelog/bug

#1671 Update "notifications" page
  docs/pages/notifications.md
Labels: netlify-cms/draft

#1677 cfpb-icons: Add numerical icons
  docs/pages/iconography.md
  packages/cfpb-icons/usage.md
Labels: lerna-changelog/enhancement
