Repository cfpb/design-system, pull requests merged in 2023-08, with the labels that each got.

#1676 Update "iconography" page
  docs/pages/iconography.md
Labels: netlify-cms/pending_publish

#1683 Update "iconography" page
  docs/pages/iconography.md
Labels: netlify-cms/pending_publish

#1685 Update "iconography" page
  docs/pages/iconography.md
Labels: netlify-cms/pending_publish

#1687 Update "iconography" page
  docs/pages/iconography.md
Labels: netlify-cms/pending_publish

#1689 Update "iconography" page
  docs/pages/iconography.md
Labels: netlify-cms/pending_publish

#1690 Update "iconography" page
  docs/pages/iconography.md
Labels: netlify-cms/pending_publish

#1691 Update "iconography" page
  docs/pages/iconography.md
Labels: netlify-cms/pending_publish

#1693 Update "iconography" page
  docs/images/uploads/icon_artboard.png
  docs/pages/iconography.md
Labels: netlify-cms/pending_publish

#1694 Update "iconography" page
  docs/images/uploads/icon_artboard_alignment.png
  docs/pages/iconography.md
Labels: netlify-cms/pending_publish

#1696 Stylelint and Prettier: Update configuration.
  .prettierrc
  .stylelintrc.cjs
  docs/admin/src/widgets/genericPreviewTemplate.js
  docs/admin/src/widgets/navigationPreviewTemplate.js
  docs/admin/src/widgets/pagePreviewTemplate.js
  docs/assets/css/skip-nav.less
  docs/assets/js/Tabs.js
  docs/assets/js/interstitial.js
  docs/assets/js/redirect-banner.js
  docs/assets/js/search.js
  docs/assets/js/toggle-details.js
  docs/pages/iconography.md
  npm-packages-offline-cache/@eslint-community-regexpp-4.6.2.tgz
  npm-packages-offline-cache/@eslint-eslintrc-2.1.1.tgz
  npm-packages-offline-cache/@eslint-js-8.46.0.tgz
  npm-packages-offline-cache/eslint-8.46.0.tgz
  npm-packages-offline-cache/eslint-config-prettier-8.9.0.tgz
  npm-packages-offline-cache/eslint-config-prettier-9.0.0.tgz
  npm-packages-offline-cache/eslint-plugin-react-7.33.1.tgz
  npm-packages-offline-cache/eslint-scope-7.2.2.tgz
  npm-packages-offline-cache/eslint-visitor-keys-3.4.2.tgz
  npm-packages-offline-cache/espree-9.6.1.tgz
  npm-packages-offline-cache/less-4.1.3.tgz
  npm-packages-offline-cache/less-4.2.0.tgz
  npm-packages-offline-cache/prettier-2.8.8.tgz
  npm-packages-offline-cache/prettier-3.0.1.tgz
  npm-packages-offline-cache/stylelint-config-prettier-9.0.5.tgz
  npm-packages-offline-cache/stylelint-config-recommended-13.0.0.tgz
  npm-packages-offline-cache/stylelint-config-standard-34.0.0.tgz
  npm-packages-offline-cache/stylelint-less-1.0.8.tgz
  package.json
  packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
  packages/cfpb-atomic-component/src/utilities/media-helpers.js
  packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
  packages/cfpb-core/src/breakpoint-state.js
  packages/cfpb-expandables/src/Expandable.js
  packages/cfpb-expandables/src/ExpandableGroup.js
  packages/cfpb-expandables/src/Summary.js
  packages/cfpb-expandables/src/SummaryMinimal.js
  packages/cfpb-forms/src/molecules/form-fields.less
  packages/cfpb-forms/src/organisms/Multiselect.js
  packages/cfpb-icons/src/icons-svg-inline.js
  packages/cfpb-layout/src/cfpb-layout.less
  packages/cfpb-layout/src/molecules/card.less
  packages/cfpb-layout/src/molecules/heroes.less
  packages/cfpb-typography/src/licensed-fonts.less
  test/browser/docs/interstitial.js
  test/browser/docs/netlify-cms.js
  test/browser/packages/cfpb-forms.js
  test/unit-test/src/cfpb-atomic-component/src/mixins/EventObserver.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/behavior.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/data-hook.spec.js
  test/unit-test/src/cfpb-atomic-component/src/utilities/transition/BaseTransition.spec.js
  test/unit-test/src/cfpb-expandables/src/Expandable.spec.js
  test/unit-test/src/cfpb-expandables/src/Summary-spec.js
  test/unit-test/src/cfpb-forms/src/organisms/MultiselectModel.spec.js
  webpack.config.docs.js
  webpack.config.packages.js
  yarn.lock
Labels: lerna-changelog/breaking

#1699 Remove problematic icon max-width property
  packages/cfpb-icons/src/cfpb-icons.less
Labels: lerna-changelog/bug

#1705 Update "paragraphs" page
  docs/pages/paragraphs.md
Labels: netlify-cms/pending_publish

#1706 Update "text-inputs" page
  docs/pages/text-inputs.md
Labels: netlify-cms/pending_publish

#1707 Update "text-inputs" page
  docs/pages/text-inputs.md
Labels: netlify-cms/pending_publish

#1708 Update "text-inputs" page
  docs/pages/text-inputs.md
Labels: netlify-cms/pending_publish

#1710 Update "links" page
  docs/pages/links.md
Labels: netlify-cms/pending_publish

#1714 Update "helper-text" page
  docs/pages/helper-text.md
Labels: netlify-cms/pending_publish
