Repository cfpb/design-system, pull requests merged in 2024-04, with the labels that each got.

#1944 cfpb-notification: Add color contrast safe colors for links in an error notification
  packages/cfpb-notifications/src/molecules/notification.less
Labels: lerna-changelog/bug

#1945 cfpb-notifications: Add links to different alerts
  docs/pages/alerts.md
  packages/cfpb-notifications/src/molecules/notification.less
Labels: lerna-changelog/enhancement

#1948 Update "typography" page
  docs/images/uploads/black_type_revised.png
  docs/images/uploads/white_type_revised.png
  docs/pages/typography.md
Labels: netlify-cms/pending_publish

#1950 fix: o-text-introduction - Limit content width to 41.875rem
  packages/cfpb-layout/src/organisms/text-introduction.less
Labels: lerna-changelog/bug

#1953 cfpb-notification: fix issue with overridden bottom margin at mobile
  docs/_includes/redirect-banner.html
  docs/pages/atomic-components.md
  docs/pages/banner-notification.md
  docs/special-pages/updating-this-website.md
  packages/cfpb-atomic-component/usage.md
  packages/cfpb-design-system/dist/cfpb-design-system.css
  packages/cfpb-design-system/dist/cfpb-design-system.css.map
  packages/cfpb-layout/dist/cfpb-layout.css
  packages/cfpb-layout/dist/cfpb-layout.css.map
  packages/cfpb-notifications/dist/cfpb-notifications.css
  packages/cfpb-notifications/dist/cfpb-notifications.css.map
  packages/cfpb-notifications/src/molecules/notification.less
  packages/cfpb-notifications/usage.md
Labels: lerna-changelog/bug

#1954 cfpb-layout: Remove `content__bleedbar`
  docs/pages/sidebars-prefooters.md
  packages/cfpb-design-system/dist/cfpb-design-system.css
  packages/cfpb-design-system/dist/cfpb-design-system.css.map
  packages/cfpb-layout/dist/cfpb-layout.css
  packages/cfpb-layout/dist/cfpb-layout.css.map
  packages/cfpb-layout/src/cfpb-layout.less
  packages/cfpb-layout/usage.md
Labels: lerna-changelog/breaking

#1957 Fix some modifiers to updated BEM | Clean up CSS nesting | add stylelint BEM rule
  docs/assets/css/color-swatches.less
  docs/assets/css/global-eyebrow.less
  docs/assets/css/grid-demo.less
  docs/assets/css/header.less
  docs/assets/css/main-content.less
  docs/assets/css/skip-nav.less
  docs/assets/css/variation.less
  docs/pages/blocks.md
  docs/pages/sidebars-prefooters.md
  docs/pages/text-inputs.md
  docs/pages/typography.md
  packages/cfpb-buttons/src/atoms/buttons-with-icons.less
  packages/cfpb-buttons/src/atoms/buttons.less
  packages/cfpb-buttons/src/molecules/button-groups.less
  packages/cfpb-core/dist/cfpb-core.css.map
  packages/cfpb-core/src/base.less
  packages/cfpb-core/src/media-queries.less
  packages/cfpb-core/src/utilities.less
  packages/cfpb-core/src/vars.less
  packages/cfpb-design-system/dist/cfpb-design-system.css
  packages/cfpb-design-system/dist/cfpb-design-system.css.map
  packages/cfpb-expandables/src/expandable.less
  packages/cfpb-expandables/src/summary.less
  packages/cfpb-forms/dist/cfpb-forms.css.map
  packages/cfpb-forms/src/atoms/form-alert.less
  packages/cfpb-forms/src/atoms/label.less
  packages/cfpb-forms/src/atoms/range.less
  packages/cfpb-forms/src/atoms/select.less
  packages/cfpb-forms/src/atoms/text-input.less
  packages/cfpb-forms/src/molecules/btn-inside-input.less
  packages/cfpb-forms/src/molecules/form-fields.less
  packages/cfpb-forms/src/organisms/form.less
  packages/cfpb-forms/src/organisms/multiselect.less
  packages/cfpb-grid/src/cfpb-grid.less
  packages/cfpb-icons/dist/cfpb-icons.css.map
  packages/cfpb-icons/src/cfpb-icons.less
  packages/cfpb-layout/dist/cfpb-layout.css
  packages/cfpb-layout/dist/cfpb-layout.css.map
  packages/cfpb-layout/src/cfpb-layout.less
  packages/cfpb-layout/src/molecules/card.less
  packages/cfpb-layout/src/organisms/card-group.less
  packages/cfpb-layout/src/organisms/email-signup.less
  packages/cfpb-layout/src/organisms/featured-content-module.less
  packages/cfpb-layout/src/organisms/wells.less
  packages/cfpb-layout/usage.md
  packages/cfpb-notifications/dist/cfpb-notifications.css
  packages/cfpb-notifications/dist/cfpb-notifications.css.map
  packages/cfpb-notifications/src/molecules/notification.less
  packages/cfpb-notifications/src/organisms/banner.less
  packages/cfpb-pagination/src/molecules/pagination.less
  packages/cfpb-tables/dist/cfpb-tables.css.map
  packages/cfpb-tables/src/cfpb-tables.less
  packages/cfpb-typography/dist/cfpb-typography.css.map
  packages/cfpb-typography/src/atoms/headings.less
  packages/cfpb-typography/src/atoms/links.less
  packages/cfpb-typography/src/atoms/tagline.less
  packages/cfpb-typography/src/molecules/list.less
  packages/cfpb-typography/src/molecules/meta-header.less
  packages/cfpb-typography/src/molecules/slug-header.less
  stylelint.config.js
Labels: lerna-changelog/bug

#1960 cfpb-typography: Remove xtra large tagline
  docs/pages/taglines.md
  packages/cfpb-design-system/dist/cfpb-design-system.css
  packages/cfpb-design-system/dist/cfpb-design-system.css.map
  packages/cfpb-typography/dist/cfpb-typography.css
  packages/cfpb-typography/dist/cfpb-typography.css.map
  packages/cfpb-typography/src/atoms/tagline.less
Labels: lerna-changelog/breaking

#1964 cfpb-typography: Remove `a-heading__icon` class
  docs/pages/variables.md
  packages/cfpb-design-system/dist/cfpb-design-system.css
  packages/cfpb-design-system/dist/cfpb-design-system.css.map
  packages/cfpb-typography/dist/cfpb-typography.css
  packages/cfpb-typography/dist/cfpb-typography.css.map
  packages/cfpb-typography/src/atoms/headings.less
  packages/cfpb-typography/src/cfpb-typography.less
  packages/cfpb-typography/usage.md
Labels: lerna-changelog/breaking
