Repository cfpb/design-system, pull requests merged in 2024-03, with the labels that each got.

#1923 cfpb-icons: Change inline SVG fill color argument to grayscale boolean flag
  docs/pages/iconography.md
  packages/cfpb-forms/src/atoms/select.less
  packages/cfpb-forms/src/molecules/form-fields.less
  packages/cfpb-icons/src/cfpb-icons.less
  packages/cfpb-icons/src/icons-svg-inline.cjs
Labels: lerna-changelog/breaking

#1925 Remove `o-expandable__padded` from docs
  packages/cfpb-expandables/usage.md
  test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers.spec.js
Labels: lerna-changelog/documentation

#1926 Remove deprecated `.a-error-message`
  packages/cfpb-design-system/dist/cfpb-design-system.css
  packages/cfpb-design-system/dist/cfpb-design-system.css.map
  packages/cfpb-forms/dist/cfpb-forms.css
  packages/cfpb-forms/dist/cfpb-forms.css.map
  packages/cfpb-forms/src/atoms/form-alert.less
  packages/cfpb-forms/src/molecules/form-fields.less
  packages/cfpb-forms/src/organisms/form.less
Labels: lerna-changelog/breaking

#1929 cfpb-layout: Remove legacy layout classes and docs
  docs/_data/side-navigation.yml
  docs/pages/blocks.md
  docs/pages/column-dividers.md
  docs/pages/sidebars-prefooters.md
  packages/cfpb-design-system/dist/cfpb-design-system.css
  packages/cfpb-design-system/dist/cfpb-design-system.css.map
  packages/cfpb-layout/dist/cfpb-layout.css
  packages/cfpb-layout/dist/cfpb-layout.css.map
  packages/cfpb-layout/src/cfpb-layout.less
Labels: lerna-changelog/breaking

#1928 cfpb-layout: Remove `content_main__narrow` class
  docs/pages/sidebars-prefooters.md
  packages/cfpb-design-system/dist/cfpb-design-system.css
  packages/cfpb-design-system/dist/cfpb-design-system.css.map
  packages/cfpb-layout/dist/cfpb-layout.css
  packages/cfpb-layout/dist/cfpb-layout.css.map
  packages/cfpb-layout/src/cfpb-layout.less
  packages/cfpb-layout/usage.md
Labels: lerna-changelog/breaking

#1935 cfpb-core: Remove `.respond-to-dpi(…)` utility
  docs/pages/media-queries.md
  packages/cfpb-core/src/media-queries.less
  packages/cfpb-core/usage.md
Labels: lerna-changelog/breaking

#1918 Migrate Less color variables to CSS custom properties (variables)
  docs/assets/css/badges.less
  docs/assets/css/color-swatches.less
  docs/assets/css/global-eyebrow.less
  docs/assets/css/grid-demo.less
  docs/assets/css/header.less
  docs/assets/css/hero.less
  docs/assets/css/main-content.less
  docs/assets/css/main.less
  docs/assets/css/search.less
  docs/assets/css/sidebar.less
  docs/assets/css/tabs.less
  docs/assets/css/variation.less
  docs/pages/heroes.md
  docs/pages/media-queries.md
  docs/pages/variables.md
  packages/cfpb-buttons/src/cfpb-buttons.less
  packages/cfpb-buttons/usage.md
  packages/cfpb-core/src/brand-colors.less
  packages/cfpb-core/src/vars.less
  packages/cfpb-core/usage.md
  packages/cfpb-expandables/src/expandable.less
  packages/cfpb-expandables/src/summary-minimal.less
  packages/cfpb-expandables/src/summary.less
  packages/cfpb-forms/src/cfpb-forms.less
  packages/cfpb-forms/src/molecules/btn-inside-input.less
  packages/cfpb-forms/src/organisms/multiselect.less
  packages/cfpb-forms/usage.md
  packages/cfpb-layout/src/cfpb-layout.less
  packages/cfpb-layout/src/molecules/card.less
  packages/cfpb-layout/src/molecules/heroes.less
  packages/cfpb-layout/src/organisms/card-group.less
  packages/cfpb-layout/src/organisms/featured-content-module.less
  packages/cfpb-layout/src/organisms/wells.less
  packages/cfpb-layout/usage.md
  packages/cfpb-notifications/src/cfpb-notifications.less
  packages/cfpb-notifications/src/organisms/banner.less
  packages/cfpb-notifications/usage.md
  packages/cfpb-pagination/src/cfpb-pagination.less
  packages/cfpb-pagination/usage.md
  packages/cfpb-tables/src/cfpb-tables.less
  packages/cfpb-tables/usage.md
  packages/cfpb-typography/src/cfpb-typography.less
  packages/cfpb-typography/usage.md
Labels: lerna-changelog/breaking

#1938 Remove unused `@text-shadow` argument
  packages/cfpb-core/src/base.less
  packages/cfpb-typography/src/atoms/date.less
  packages/cfpb-typography/src/molecules/pull-quote.less
Labels: lerna-changelog/bug

#1940 cfpb-notifications: Only set icon color on first child icon | move h4 to CSS
  docs/pages/alerts.md
  packages/cfpb-design-system/dist/cfpb-design-system.css
  packages/cfpb-design-system/dist/cfpb-design-system.css.map
  packages/cfpb-notifications/dist/cfpb-notifications.css
  packages/cfpb-notifications/dist/cfpb-notifications.css.map
  packages/cfpb-notifications/src/molecules/notification.less
Labels: lerna-changelog/bug

#1930 cfpb-expandables: Set spacing for expandable icon
  docs/pages/expandables.md
  docs/pages/filterable-list-control-panels.md
  docs/special-pages/updating-this-website.md
  packages/cfpb-expandables/src/expandable.less
  packages/cfpb-expandables/usage.md
Labels: lerna-changelog/breaking
