Repository cfpb/design-system, pull requests merged in 2024-02, with the labels that each got.

#1902 Update node to v20
  .github/workflows/lighthouse.yml
  .github/workflows/pages.yml
  .github/workflows/publish.yml
  .github/workflows/sauce.yml
  .github/workflows/tests-unit.yml
Labels: lerna-changelog/internal

#1907 cfpb-expandables: Fix incorrect selector target
  packages/cfpb-expandables/src/expandable.less
Labels: lerna-changelog/bug

#1911 Add range slider component
  .github/workflows/pages.yml
  Gemfile
  README.md
  docs/images/uploads/slider-default.png
  docs/images/uploads/slider-focus.png
  docs/pages/range-sliders.md
  packages/cfpb-forms/src/atoms/range.less
  packages/cfpb-forms/src/cfpb-forms.less
Labels: lerna-changelog/enhancement

#1914 cfpb-forms: Add min-height to range slider
  packages/cfpb-design-system/dist/cfpb-design-system.css
  packages/cfpb-design-system/dist/cfpb-design-system.css.map
  packages/cfpb-forms/dist/cfpb-forms.css
  packages/cfpb-forms/dist/cfpb-forms.css.map
  packages/cfpb-forms/src/atoms/range.less
Labels: lerna-changelog/bug

#1915 cfpb-typography: Remove older WOFF files
  esbuild/docs/build.js
  esbuild/packages/build.js
  packages/cfpb-typography/src/licensed-fonts.less
  scripts/fonts.sh
Labels: lerna-changelog/breaking
