Repository cfpb/design-system, pull requests merged in 2024-08, with the labels that each got.

#2011 Update "banner-notification" page
  docs/pages/banner-notification.md
Labels: netlify-cms/pending_publish

#2009 Remove `a-legend` class | Move legends inside fieldsets
  docs/pages/fieldsets.md
  docs/pages/filterable-list-control-panels.md
  docs/pages/labels.md
  packages/cfpb-forms/src/atoms/legend.less
  packages/cfpb-forms/src/atoms/legend.scss
  packages/cfpb-forms/src/cfpb-forms.less
  packages/cfpb-forms/src/cfpb-forms.scss
  packages/cfpb-forms/usage.md
Labels: lerna-changelog/breaking

#2014 Update banner color scheme
  packages/cfpb-design-system/src/components/cfpb-notifications/banner.scss
Labels: lerna-changelog/bug

#2018 Remove default export
  packages/cfpb-design-system/src/abstracts/index.js
  packages/cfpb-design-system/src/abstracts/vars-breakpoints.js
  packages/cfpb-design-system/src/utilities/breakpoint-state.js
Labels: lerna-changelog/enhancement

#2022 Create root package index.scss
  packages/cfpb-design-system/src/index.scss
Labels: lerna-changelog/enhancement

#1844 Update "tags" page
  docs/pages/tags.md
Labels: netlify-cms/pending_publish

#2023 Update "side-navigation" page
  docs/_data/side-navigation.yml
Labels: netlify-cms/pending_publish

#2024 FCM: Unquote padding-bottom value in video-playing class
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-notifications/index.css
  packages/cfpb-design-system/dist/components/cfpb-notifications/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-notifications/index.js.map
  packages/cfpb-design-system/dist/index.css
  packages/cfpb-design-system/dist/index.css.map
  packages/cfpb-design-system/dist/index.js.map
  packages/cfpb-design-system/dist/utilities/index.css
  packages/cfpb-design-system/dist/utilities/index.css.map
  packages/cfpb-design-system/dist/utilities/index.js.map
  packages/cfpb-design-system/src/utilities/utilities.scss
Labels: lerna-changelog/bug

#2029 Fix malformed line-height
  packages/cfpb-design-system/src/components/cfpb-typography/meta-header.scss
Labels: lerna-changelog/bug

#2028 Linter autofixes
  docs/assets/css/main.scss
  packages/cfpb-design-system/src/index.scss
Labels: lerna-changelog/internal
