Repository cfpb/design-system, pull requests merged in 2024-09, with the labels that each got.

#2034 Update accordion BEM fix
  docs/pages/expandables.md
  docs/special-pages/updating-this-website.md
  packages/cfpb-design-system/src/components/cfpb-expandables/expandable-group.js
  packages/cfpb-design-system/src/components/cfpb-expandables/expandable.spec.js
Labels: lerna-changelog/bug

#2027 Remove `$font-size` variable
  packages/cfpb-design-system/src/abstracts/heading-mixins.scss
  packages/cfpb-design-system/src/components/cfpb-typography/slug-header.scss
Labels: lerna-changelog/breaking

#2036 Adjust tags outline and coloring
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-typography/index.css
  packages/cfpb-design-system/dist/components/cfpb-typography/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-typography/index.js
  packages/cfpb-design-system/dist/components/cfpb-typography/index.js.map
  packages/cfpb-design-system/dist/index.css
  packages/cfpb-design-system/dist/index.css.map
  packages/cfpb-design-system/dist/index.js.map
  packages/cfpb-design-system/dist/utilities/index.css
  packages/cfpb-design-system/dist/utilities/index.css.map
  packages/cfpb-design-system/dist/utilities/index.js.map
  packages/cfpb-design-system/src/components/cfpb-forms/tag.scss
  packages/cfpb-design-system/src/components/cfpb-typography/mixins.scss
Labels: lerna-changelog/bug

#2038 Add tag RTL code
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js.map
  packages/cfpb-design-system/dist/index.css
  packages/cfpb-design-system/dist/index.css.map
  packages/cfpb-design-system/dist/index.js.map
  packages/cfpb-design-system/dist/utilities/index.css
  packages/cfpb-design-system/dist/utilities/index.css.map
  packages/cfpb-design-system/dist/utilities/index.js.map
  packages/cfpb-design-system/src/components/cfpb-forms/tag.scss
Labels: lerna-changelog/enhancement

#2037 Adjust focus rectangle offset for default links, expandables, summaries
  packages/cfpb-design-system/dist/base/index.css
  packages/cfpb-design-system/dist/base/index.css.map
  packages/cfpb-design-system/dist/base/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js.map
  packages/cfpb-design-system/dist/index.css
  packages/cfpb-design-system/dist/index.css.map
  packages/cfpb-design-system/dist/index.js.map
  packages/cfpb-design-system/dist/utilities/index.css
  packages/cfpb-design-system/dist/utilities/index.css.map
  packages/cfpb-design-system/dist/utilities/index.js.map
  packages/cfpb-design-system/src/base/base.scss
  packages/cfpb-design-system/src/components/cfpb-expandables/expandable.scss
  packages/cfpb-design-system/src/components/cfpb-expandables/summary-minimal.scss
  packages/cfpb-design-system/src/components/cfpb-expandables/summary.scss
Labels: lerna-changelog/bug

#2041 Update "seal" page
  docs/pages/seal.md
Labels: decap-cms/pending_publish

#2042 Add stacked topic tag group modifier
  docs/pages/tags.md
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js.map
  packages/cfpb-design-system/dist/index.css
  packages/cfpb-design-system/dist/index.css.map
  packages/cfpb-design-system/dist/index.js.map
  packages/cfpb-design-system/dist/utilities/index.css
  packages/cfpb-design-system/dist/utilities/index.css.map
  packages/cfpb-design-system/dist/utilities/index.js.map
  packages/cfpb-design-system/src/components/cfpb-forms/tag.scss
Labels: lerna-changelog/enhancement

#2045 Add non-link topic tags
  docs/pages/tags.md
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-typography/index.css
  packages/cfpb-design-system/dist/components/cfpb-typography/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-typography/index.js.map
  packages/cfpb-design-system/dist/index.css
  packages/cfpb-design-system/dist/index.css.map
  packages/cfpb-design-system/dist/index.js.map
  packages/cfpb-design-system/dist/utilities/index.css
  packages/cfpb-design-system/dist/utilities/index.css.map
  packages/cfpb-design-system/dist/utilities/index.js.map
  packages/cfpb-design-system/src/components/cfpb-forms/tag.scss
  packages/cfpb-design-system/src/components/cfpb-typography/link.scss
  packages/cfpb-design-system/src/components/cfpb-typography/mixins.scss
Labels: lerna-changelog/enhancement

#2046 Update gap in tags
  packages/cfpb-design-system/src/components/cfpb-forms/tag.scss
Labels: lerna-changelog/bug

#2043 Combine build scripts
  .github/workflows/publish.yml
  CONTRIBUTING.md
  package.json
  scripts/pre-release.sh
Labels: lerna-changelog/internal

#2048 Restructure and update development docs
  CONTRIBUTING.md
  README.md
  docs/_data/side-navigation.yml
  docs/admin/config.yml
  docs/assets/css/layout.scss
  docs/assets/css/skip-nav.scss
  docs/pages/alerts.md
  docs/pages/atomic-components.md
  docs/pages/base-images.md
  docs/pages/blocks.md
  docs/pages/buttons.md
  docs/pages/expandables.md
  docs/pages/featured-content-modules.md
  docs/pages/getting-started.md
  docs/pages/grid.md
  docs/pages/heading-hierarchy.md
  docs/pages/helper-text.md
  docs/pages/heroes.md
  docs/pages/info-unit-groups-link-blobs.md
  docs/pages/integrating-the-design-system-into-your-project.md
  docs/pages/links.md
  docs/pages/pagination.md
  docs/pages/paragraphs.md
  docs/pages/selects.md
  docs/pages/sidebars-prefooters.md
  docs/pages/tables.md
  docs/pages/tags.md
  docs/pages/text-inputs.md
  docs/pages/typography.md
  docs/pages/variables.md
  docs/special-pages/home.md
  scripts/pre-release.sh
Labels: lerna-changelog/internal

#2049 Replace multiselect tags with filter tags
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js.map
  packages/cfpb-design-system/dist/index.css
  packages/cfpb-design-system/dist/index.css.map
  packages/cfpb-design-system/dist/index.js
  packages/cfpb-design-system/dist/index.js.map
  packages/cfpb-design-system/dist/utilities/index.css
  packages/cfpb-design-system/dist/utilities/index.css.map
  packages/cfpb-design-system/dist/utilities/index.js
  packages/cfpb-design-system/dist/utilities/index.js.map
  packages/cfpb-design-system/src/components/cfpb-forms/multiselect.js
  packages/cfpb-design-system/src/components/cfpb-forms/multiselect.scss
  packages/cfpb-design-system/src/components/cfpb-forms/multiselect.spec.js
  packages/cfpb-design-system/src/components/cfpb-forms/tag.scss
  test/cypress/e2e/packages/cfpb-forms.cy.js
Labels: lerna-changelog/enhancement

#2053 More color contrast adjustments | Formatting fixes
  docs/assets/css/code.scss
  docs/pages/grid.md
  docs/pages/helper-classes-mixins.md
  docs/pages/media-queries.md
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-notifications/index.css
  packages/cfpb-design-system/dist/components/cfpb-notifications/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-notifications/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-typography/index.css
  packages/cfpb-design-system/dist/components/cfpb-typography/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-typography/index.js.map
  packages/cfpb-design-system/dist/index.css
  packages/cfpb-design-system/dist/index.css.map
  packages/cfpb-design-system/dist/index.js.map
  packages/cfpb-design-system/dist/utilities/index.css
  packages/cfpb-design-system/dist/utilities/index.css.map
  packages/cfpb-design-system/dist/utilities/index.js.map
  packages/cfpb-design-system/src/utilities/utilities.scss
Labels: lerna-changelog/bug

#2057 Update "tags" page
  docs/pages/tags.md
Labels: decap-cms/pending_publish

#2055 Refactor heading mixins
  docs/assets/css/tabs.scss
  packages/cfpb-design-system/dist/base/index.css
  packages/cfpb-design-system/dist/base/index.css.map
  packages/cfpb-design-system/dist/base/index.js
  packages/cfpb-design-system/dist/base/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js
  packages/cfpb-design-system/dist/components/cfpb-expandables/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css
  packages/cfpb-design-system/dist/components/cfpb-forms/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js
  packages/cfpb-design-system/dist/components/cfpb-forms/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-layout/index.css
  packages/cfpb-design-system/dist/components/cfpb-layout/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-layout/index.js
  packages/cfpb-design-system/dist/components/cfpb-layout/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-tables/index.css
  packages/cfpb-design-system/dist/components/cfpb-tables/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-tables/index.js
  packages/cfpb-design-system/dist/components/cfpb-tables/index.js.map
  packages/cfpb-design-system/dist/components/cfpb-typography/index.css
  packages/cfpb-design-system/dist/components/cfpb-typography/index.css.map
  packages/cfpb-design-system/dist/components/cfpb-typography/index.js
  packages/cfpb-design-system/dist/components/cfpb-typography/index.js.map
  packages/cfpb-design-system/dist/index.css
  packages/cfpb-design-system/dist/index.css.map
  packages/cfpb-design-system/dist/index.js
  packages/cfpb-design-system/dist/index.js.map
  packages/cfpb-design-system/dist/utilities/index.css
  packages/cfpb-design-system/dist/utilities/index.css.map
  packages/cfpb-design-system/dist/utilities/index.js
  packages/cfpb-design-system/dist/utilities/index.js.map
  packages/cfpb-design-system/src/abstracts/heading-mixins.scss
  packages/cfpb-design-system/src/base/base.scss
  packages/cfpb-design-system/src/components/cfpb-forms/label.scss
  packages/cfpb-design-system/src/components/cfpb-layout/card-group.scss
  packages/cfpb-design-system/src/components/cfpb-layout/card.scss
  packages/cfpb-design-system/src/components/cfpb-layout/hero.scss
  packages/cfpb-design-system/src/components/cfpb-tables/table.scss
  packages/cfpb-design-system/src/components/cfpb-typography/date.scss
  packages/cfpb-design-system/src/components/cfpb-typography/meta-header.scss
  packages/cfpb-design-system/src/components/cfpb-typography/pull-quote.scss
  packages/cfpb-design-system/src/components/cfpb-typography/slug-header.scss
Labels: lerna-changelog/breaking
